spring.application.name=University-Management-System

# ===============================
# APPLICATION INFO
# ===============================
app.version=1.0.0
app.environment=development

# ===============================
# SERVER
# ===============================
server.port=8081
#server.servlet.context-path=/api


# ===============================
# LOCAL DEV (DOCKER DISABLED)
# ===============================
spring.docker.compose.enabled=false
spring.docker.compose.lifecycle-management=none


# ===============================
# DATABASE CONFIGURATION
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/unidata
spring.datasource.username=uniuser
spring.datasource.password=unipass
spring.datasource.driver-class-name=org.postgresql.Driver


# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=true

# ? REQUIRED FOR FLYWAY + VALIDATE
#spring.jpa.defer-datasource-initialization=true
#
#spring.jpa.properties.hibernate.id.new_generator_mappings=true


# ===============================
# HIKARI CONNECTION POOL
# ===============================
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.max-lifetime=1800000


# ===============================
# FLYWAY
# ===============================
#spring.flyway.enabled=true
#spring.flyway.locations=classpath:db/migration
#spring.flyway.baseline-on-migrate=true
#spring.flyway.validate-on-migrate=true


# ===============================
# LOGGING
# ===============================
logging.level.root=INFO
logging.level.com.university=INFO
logging.level.org.springframework=WARN
logging.level.org.hibernate=WARN
#logging.level.org.flywaydb=INFO



# ===============================
# ACTUATOR
# ===============================
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=never


# ===============================
# REDIS
# ===============================
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.timeout=5s
#spring.data.redis.username=${REDIS_USERNAME:}
#spring.data.redis.password=${REDIS_PASSWORD:}
spring.cache.type=${SPRING_CACHE_TYPE:simple}
spring.cache.redis.time-to-live=45m
spring.cache.redis.cache-null-values=false
spring.cache.redis.use-key-prefix=true
spring.cache.redis.key-prefix=ums:v2:
